# Gangetabell og lister

**Læringsmål:**

* Løkker
* Lister




## Oppgave a: obligatorisk

Lag en funksjon separate(numbers, threshold) som tar inn to argumenter:

* numbers: en liste med heltall
* threshold: et heltall

Funksjonen skal returnere to lister: den første listen skal inneholde alle elementer fra **numbers** som er mindre enn **threshold**, og den andre listen skal inneholde alle elementer fra **numbers** som er større enn eller lik **threshold**.

 
En matrise er et rektangulært sett av elementer ordnet i rader og kolonner. Radene er de horisontale linjene, og kolonnene er de vertikale linjene.

I Python representerer vi dette med lister som inneholder lister.  Elementet øverst til venstre i eksempelet under (med verdi 1) er i rad 1, kolonne 1.

In [1]:
matrise = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]

Elementene i matrisen kan hentes ut på følgende måte: **matrise[radnr][kolnr]**. 

*Husk at radnummer og kolonnenummer er null-indeksert (begynner på 0) i Python i motsetning til matematisk notasjon der de er 1-indeksert!*

***Skriv koden din i boksen under.***

In [2]:
def separate(numbers, threshold):
    smaller = []
    larger = []

    for num in numbers:
        if num < threshold:
            smaller.append(num)
        else:
            larger.append(num)
    return smaller, larger


# Testing
testNums = [2, 3, 4, 5, 6, 10, 1, 2, 3]
threshold = 5
smaller, larger = separate(testNums, threshold)

print(smaller)
print(larger)



[2, 3, 4, 1, 2, 3]
[5, 6, 10]


## Oppgave b: obligatorisk

Lag en funksjon **multiplication_table(n)** som tar inn et heltall n som parameter og returnerer gangetabellen fra 1 til n som en matrise med n rader og n kolonner.

***Skriv koden din i boksen under.***

In [17]:
import numpy as np
def multiplication_table(n):
    output = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            output[i][j] = (i+1)*(j+1)
    return output

Har du implementert funksjon riktig skal koden under printe følgende matrise:


```
[[1, 2, 3, 4],
 [2, 4, 6, 8],
 [3, 6, 9, 12],
 [4, 8, 12, 16]]
 ```

In [18]:
print(multiplication_table(4))

[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]


#### Hint

Man kan legge til elementer (som også kan være lister) på slutten av en liste med **liste.append(element)**.